server:
  port: 8080

cloud:
  aws:
    region:
      static: us-east-1
    credentials:
      access-key: AKIAJLS5S4G7UYQ2LUMQ
      secret-key: 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
s3:
  bucket: theground

